In [1]:
import pandas as pd
import numpy as np

In [2]:
f1=pd.read_csv('D.csv')

/var/folders/l6/736l2wjj1cx0g8_mdb43qr8c0000gn/T/ipykernel_38047/1518554091.py:1: DtypeWarning: Columns (1,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  f1=pd.read_csv('D.csv')

In [3]:
f1.head(10)

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,eliminator,players_count,innings_total_runs,innings_wickets,innings_legal_balls,innings_overs,delivery_total_runs,innings_runs_after_ball,innings_wickets_after_ball,innings_score_after_ball
0,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",1,0.1,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,S Dhawan,...,NaN,22,207,4,120,20.0,0,0,0,0/0
1,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",1,0.2,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,S Dhawan,...,NaN,22,207,4,120,20.0,0,0,0,0/0
2,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",1,0.3,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,S Dhawan,...,NaN,22,207,4,120,20.0,4,4,0,4/0
3,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",1,0.4,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,S Dhawan,...,NaN,22,207,4,120,20.0,0,4,0,4/0
4,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",1,0.5,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,S Dhawan,...,NaN,22,207,4,120,20.0,2,6,0,6/0
5,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",1,0.6,Sunrisers Hyderabad,Royal Challengers Bangalore,S Dhawan,DA Warner,...,NaN,22,207,4,120,20.0,0,6,0,6/0
6,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",1,0.7,Sunrisers Hyderabad,Royal Challengers Bangalore,S Dhawan,DA Warner,...,NaN,22,207,4,120,20.0,1,7,0,7/0
7,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",1,1.1,Sunrisers Hyderabad,Royal Challengers Bangalore,S Dhawan,DA Warner,...,NaN,22,207,4,120,20.0,1,8,0,8/0
8,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",1,1.2,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,S Dhawan,...,NaN,22,207,4,120,20.0,4,12,0,12/0
9,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",1,1.3,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,S Dhawan,...,NaN,22,207,4,120,20.0,1,13,0,13/0

In [4]:
f1.tail()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,eliminator,players_count,innings_total_runs,innings_wickets,innings_legal_balls,innings_overs,delivery_total_runs,innings_runs_after_ball,innings_wickets_after_ball,innings_score_after_ball
295727,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.2,Royal Challengers Bangalore,Sunrisers Hyderabad,Sachin Baby,CJ Jordan,...,NaN,22,200,7,120,20.0,2,194,6,194/6
295728,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.3,Royal Challengers Bangalore,Sunrisers Hyderabad,Sachin Baby,CJ Jordan,...,NaN,22,200,7,120,20.0,0,194,7,194/7
295729,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.4,Royal Challengers Bangalore,Sunrisers Hyderabad,Iqbal Abdulla,Sachin Baby,...,NaN,22,200,7,120,20.0,1,195,7,195/7
295730,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.5,Royal Challengers Bangalore,Sunrisers Hyderabad,Sachin Baby,Iqbal Abdulla,...,NaN,22,200,7,120,20.0,1,196,7,196/7
295731,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.6,Royal Challengers Bangalore,Sunrisers Hyderabad,Iqbal Abdulla,Sachin Baby,...,NaN,22,200,7,120,20.0,4,200,7,200/7

In [5]:
second =f1[f1['innings']==2].copy()

In [6]:
second

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,eliminator,players_count,innings_total_runs,innings_wickets,innings_legal_balls,innings_overs,delivery_total_runs,innings_runs_after_ball,innings_wickets_after_ball,innings_score_after_ball
125,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.1,Royal Challengers Bangalore,Sunrisers Hyderabad,CH Gayle,Mandeep Singh,...,NaN,22,172,10,118,19.4,1,1,0,1/0
126,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.2,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,NaN,22,172,10,118,19.4,0,1,0,1/0
127,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.3,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,NaN,22,172,10,118,19.4,0,1,0,1/0
128,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.4,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,NaN,22,172,10,118,19.4,2,3,0,3/0
129,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.5,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,NaN,22,172,10,118,19.4,4,7,0,7/0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295727,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.2,Royal Challengers Bangalore,Sunrisers Hyderabad,Sachin Baby,CJ Jordan,...,NaN,22,200,7,120,20.0,2,194,6,194/6
295728,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.3,Royal Challengers Bangalore,Sunrisers Hyderabad,Sachin Baby,CJ Jordan,...,NaN,22,200,7,120,20.0,0,194,7,194/7
295729,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.4,Royal Challengers Bangalore,Sunrisers Hyderabad,Iqbal Abdulla,Sachin Baby,...,NaN,22,200,7,120,20.0,1,195,7,195/7
295730,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.5,Royal Challengers Bangalore,Sunrisers Hyderabad,Sachin Baby,Iqbal Abdulla,...,NaN,22,200,7,120,20.0,1,196,7,196/7
295731,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.6,Royal Challengers Bangalore,Sunrisers Hyderabad,Iqbal Abdulla,Sachin Baby,...,NaN,22,200,7,120,20.0,4,200,7,200/7

In [7]:
first=f1[f1['innings']==1].copy()

In [8]:
first

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,eliminator,players_count,innings_total_runs,innings_wickets,innings_legal_balls,innings_overs,delivery_total_runs,innings_runs_after_ball,innings_wickets_after_ball,innings_score_after_ball
0,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",1,0.1,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,S Dhawan,...,NaN,22,207,4,120,20.0,0,0,0,0/0
1,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",1,0.2,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,S Dhawan,...,NaN,22,207,4,120,20.0,0,0,0,0/0
2,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",1,0.3,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,S Dhawan,...,NaN,22,207,4,120,20.0,4,4,0,4/0
3,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",1,0.4,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,S Dhawan,...,NaN,22,207,4,120,20.0,0,4,0,4/0
4,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",1,0.5,Sunrisers Hyderabad,Royal Challengers Bangalore,DA Warner,S Dhawan,...,NaN,22,207,4,120,20.0,2,6,0,6/0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295603,981019,2016,2016-05-29,M Chinnaswamy Stadium,1,19.2,Sunrisers Hyderabad,Royal Challengers Bangalore,BCJ Cutting,B Kumar,...,NaN,22,208,7,120,20.0,6,194,7,194/7
295604,981019,2016,2016-05-29,M Chinnaswamy Stadium,1,19.3,Sunrisers Hyderabad,Royal Challengers Bangalore,BCJ Cutting,B Kumar,...,NaN,22,208,7,120,20.0,6,200,7,200/7
295605,981019,2016,2016-05-29,M Chinnaswamy Stadium,1,19.4,Sunrisers Hyderabad,Royal Challengers Bangalore,BCJ Cutting,B Kumar,...,NaN,22,208,7,120,20.0,1,201,7,201/7
295606,981019,2016,2016-05-29,M Chinnaswamy Stadium,1,19.5,Sunrisers Hyderabad,Royal Challengers Bangalore,B Kumar,BCJ Cutting,...,NaN,22,208,7,120,20.0,1,202,7,202/7
295607,981019,2016,2016-05-29,M Chinnaswamy Stadium,1,19.6,Sunrisers Hyderabad,Royal Challengers Bangalore,BCJ Cutting,B Kumar,...,NaN,22,208,7,120,20.0,6,208,7,208/7

In [11]:
target_df=first[['match_id','innings_total_runs']].drop_duplicates()

In [13]:
target_df

        match_id  innings_total_runs
0        1082591                 207
248      1082592                 184
495      1082593                 183
713      1082594                 163
960      1082595                 157
...          ...                 ...
294520    981011                 138
294756    981013                 158
294996    981015                 162
295240    981017                 162
295482    981019                 208

[1243 rows x 2 columns]

In [14]:
target_df['target']=target_df['innings_total_runs']+1

In [16]:
target_df

        match_id  innings_total_runs  target
0        1082591                 207     208
248      1082592                 184     185
495      1082593                 183     184
713      1082594                 163     164
960      1082595                 157     158
...          ...                 ...     ...
294520    981011                 138     139
294756    981013                 158     159
294996    981015                 162     163
295240    981017                 162     163
295482    981019                 208     209

[1243 rows x 3 columns]

In [17]:
#merging the target score into second innings dataset

In [18]:
second=second.merge(target_df[['match_id','target']],on='match_id')

In [19]:
second

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,players_count,innings_total_runs,innings_wickets,innings_legal_balls,innings_overs,delivery_total_runs,innings_runs_after_ball,innings_wickets_after_ball,innings_score_after_ball,target
0,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.1,Royal Challengers Bangalore,Sunrisers Hyderabad,CH Gayle,Mandeep Singh,...,22,172,10,118,19.4,1,1,0,1/0,208
1,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.2,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,22,172,10,118,19.4,0,1,0,1/0,208
2,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.3,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,22,172,10,118,19.4,0,1,0,1/0,208
3,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.4,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,22,172,10,118,19.4,2,3,0,3/0,208
4,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.5,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,22,172,10,118,19.4,4,7,0,7/0,208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142298,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.2,Royal Challengers Bangalore,Sunrisers Hyderabad,Sachin Baby,CJ Jordan,...,22,200,7,120,20.0,2,194,6,194/6,209
142299,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.3,Royal Challengers Bangalore,Sunrisers Hyderabad,Sachin Baby,CJ Jordan,...,22,200,7,120,20.0,0,194,7,194/7,209
142300,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.4,Royal Challengers Bangalore,Sunrisers Hyderabad,Iqbal Abdulla,Sachin Baby,...,22,200,7,120,20.0,1,195,7,195/7,209
142301,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.5,Royal Challengers Bangalore,Sunrisers Hyderabad,Sachin Baby,Iqbal Abdulla,...,22,200,7,120,20.0,1,196,7,196/7,209
142302,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.6,Royal Challengers Bangalore,Sunrisers Hyderabad,Iqbal Abdulla,Sachin Baby,...,22,200,7,120,20.0,4,200,7,200/7,209

In [ ]:
#current score is equal to innings runs after ball

In [21]:
second['current_score']=second['innings_runs_after_ball']

In [22]:
second

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,innings_total_runs,innings_wickets,innings_legal_balls,innings_overs,delivery_total_runs,innings_runs_after_ball,innings_wickets_after_ball,innings_score_after_ball,target,current_score
0,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.1,Royal Challengers Bangalore,Sunrisers Hyderabad,CH Gayle,Mandeep Singh,...,172,10,118,19.4,1,1,0,1/0,208,1
1,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.2,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,172,10,118,19.4,0,1,0,1/0,208,1
2,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.3,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,172,10,118,19.4,0,1,0,1/0,208,1
3,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.4,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,172,10,118,19.4,2,3,0,3/0,208,3
4,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.5,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,172,10,118,19.4,4,7,0,7/0,208,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142298,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.2,Royal Challengers Bangalore,Sunrisers Hyderabad,Sachin Baby,CJ Jordan,...,200,7,120,20.0,2,194,6,194/6,209,194
142299,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.3,Royal Challengers Bangalore,Sunrisers Hyderabad,Sachin Baby,CJ Jordan,...,200,7,120,20.0,0,194,7,194/7,209,194
142300,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.4,Royal Challengers Bangalore,Sunrisers Hyderabad,Iqbal Abdulla,Sachin Baby,...,200,7,120,20.0,1,195,7,195/7,209,195
142301,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.5,Royal Challengers Bangalore,Sunrisers Hyderabad,Sachin Baby,Iqbal Abdulla,...,200,7,120,20.0,1,196,7,196/7,209,196
142302,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.6,Royal Challengers Bangalore,Sunrisers Hyderabad,Iqbal Abdulla,Sachin Baby,...,200,7,120,20.0,4,200,7,200/7,209,200

In [23]:
second['runs_left']=second['target']-second['current_score']

In [24]:
second

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,innings_wickets,innings_legal_balls,innings_overs,delivery_total_runs,innings_runs_after_ball,innings_wickets_after_ball,innings_score_after_ball,target,current_score,runs_left
0,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.1,Royal Challengers Bangalore,Sunrisers Hyderabad,CH Gayle,Mandeep Singh,...,10,118,19.4,1,1,0,1/0,208,1,207
1,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.2,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,10,118,19.4,0,1,0,1/0,208,1,207
2,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.3,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,10,118,19.4,0,1,0,1/0,208,1,207
3,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.4,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,10,118,19.4,2,3,0,3/0,208,3,205
4,1082591,2017,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",2,0.5,Royal Challengers Bangalore,Sunrisers Hyderabad,Mandeep Singh,CH Gayle,...,10,118,19.4,4,7,0,7/0,208,7,201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142298,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.2,Royal Challengers Bangalore,Sunrisers Hyderabad,Sachin Baby,CJ Jordan,...,7,120,20.0,2,194,6,194/6,209,194,15
142299,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.3,Royal Challengers Bangalore,Sunrisers Hyderabad,Sachin Baby,CJ Jordan,...,7,120,20.0,0,194,7,194/7,209,194,15
142300,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.4,Royal Challengers Bangalore,Sunrisers Hyderabad,Iqbal Abdulla,Sachin Baby,...,7,120,20.0,1,195,7,195/7,209,195,14
142301,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.5,Royal Challengers Bangalore,Sunrisers Hyderabad,Sachin Baby,Iqbal Abdulla,...,7,120,20.0,1,196,7,196/7,209,196,13
142302,981019,2016,2016-05-29,M Chinnaswamy Stadium,2,19.6,Royal Challengers Bangalore,Sunrisers Hyderabad,Iqbal Abdulla,Sachin Baby,...,7,120,20.0,4,200,7,200/7,209,200,9

In [25]:
second.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed', 'city', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'winner', 'winner_runs', 'winner_wickets', 'result',
       'player_of_match', 'event', 'match_number', 'gender', 'dates',
       'balls_per_over', 'method', 'eliminator', 'players_count',
       'innings_total_runs', 'innings_wickets', 'innings_legal_balls',
       'innings_overs', 'delivery_total_runs', 'innings_runs_after_ball',
       'innings_wickets_after_ball', 'innings_score_after_ball', 'target',
       'current_score', 'runs_left'],
      dtype='object')

In [26]:
second[['match_id','ball','innings_legal_balls']].head(20)

    match_id  ball  innings_legal_balls
0    1082591   0.1                  118
1    1082591   0.2                  118
2    1082591   0.3                  118
3    1082591   0.4                  118
4    1082591   0.5                  118
5    1082591   0.6                  118
6    1082591   1.1                  118
7    1082591   1.2                  118
8    1082591   1.3                  118
9    1082591   1.4                  118
10   1082591   1.5                  118
11   1082591   1.6                  118
12   1082591   2.1                  118
13   1082591   2.2                  118
14   1082591   2.3                  118
15   1082591   2.4                  118
16   1082591   2.5                  118
17   1082591   2.6                  118
18   1082591   3.1                  118
19   1082591   3.2                  118

In [27]:
second[second['match_id']==1082591][['ball','innings_legal_balls']].head(20)

    ball  innings_legal_balls
0    0.1                  118
1    0.2                  118
2    0.3                  118
3    0.4                  118
4    0.5                  118
5    0.6                  118
6    1.1                  118
7    1.2                  118
8    1.3                  118
9    1.4                  118
10   1.5                  118
11   1.6                  118
12   2.1                  118
13   2.2                  118
14   2.3                  118
15   2.4                  118
16   2.5                  118
17   2.6                  118
18   3.1                  118
19   3.2                  118

In [31]:
second['balls_bowled']=second.groupby('match_id').cumcount()+1

In [37]:
second['wickets_left'] = 10 - second['innings_wickets_after_ball']

In [46]:
second[['ball','innings_legal_balls']].tail(20)

        ball  innings_legal_balls
142283  16.5                  120
142284  16.6                  120
142285  17.1                  120
142286  17.2                  120
142287  17.3                  120
142288  17.4                  120
142289  17.5                  120
142290  17.6                  120
142291  18.1                  120
142292  18.2                  120
142293  18.3                  120
142294  18.4                  120
142295  18.5                  120
142296  18.6                  120
142297  19.1                  120
142298  19.2                  120
142299  19.3                  120
142300  19.4                  120
142301  19.5                  120
142302  19.6                  120

In [47]:
second[['ball','innings_legal_balls']].head(20)

    ball  innings_legal_balls
0    0.1                  118
1    0.2                  118
2    0.3                  118
3    0.4                  118
4    0.5                  118
5    0.6                  118
6    1.1                  118
7    1.2                  118
8    1.3                  118
9    1.4                  118
10   1.5                  118
11   1.6                  118
12   2.1                  118
13   2.2                  118
14   2.3                  118
15   2.4                  118
16   2.5                  118
17   2.6                  118
18   3.1                  118
19   3.2                  118

In [48]:
second['balls_left'] = 120 - second['balls_bowled']

In [49]:
second['balls_bowled'].max()

136

In [50]:
second['balls_left'].min()

-16

In [51]:
second[second['balls_bowled'] > 120][['match_id','ball','balls_bowled']].head(20)

      match_id  ball  balls_bowled
120    1082591  19.2           121
121    1082591  19.3           122
122    1082591  19.4           123
243    1082592  19.4           121
244    1082592  19.5           122
461    1082594  18.6           121
462    1082594  18.7           122
583    1082595  19.3           121
584    1082595  19.4           122
585    1082595  19.5           123
586    1082595  19.6           124
803    1082597  18.7           121
804    1082597  19.1           122
805    1082597  19.2           123
806    1082597  19.3           124
807    1082597  19.4           125
808    1082597  19.5           126
1567   1082604  19.3           121
1568   1082604  19.4           122
1569   1082604  19.5           123

In [53]:
second[['ball','wides','noballs','legal_ball']].head(20)

    ball  wides  noballs  legal_ball
0    0.1    NaN      NaN           0
1    0.2    NaN      NaN           0
2    0.3    NaN      NaN           0
3    0.4    NaN      NaN           0
4    0.5    NaN      NaN           0
5    0.6    NaN      NaN           0
6    1.1    NaN      NaN           0
7    1.2    NaN      NaN           0
8    1.3    NaN      NaN           0
9    1.4    NaN      NaN           0
10   1.5    NaN      NaN           0
11   1.6    NaN      NaN           0
12   2.1    NaN      NaN           0
13   2.2    NaN      NaN           0
14   2.3    NaN      NaN           0
15   2.4    NaN      NaN           0
16   2.5    NaN      NaN           0
17   2.6    NaN      NaN           0
18   3.1    NaN      NaN           0
19   3.2    NaN      NaN           0

In [54]:
second['wides'] = second['wides'].fillna(0)
second['noballs'] = second['noballs'].fillna(0)

In [55]:
second['legal_ball'] = ((second['wides'] == 0) & (second['noballs'] == 0)).astype(int)

In [56]:
second[['ball','wides','noballs','legal_ball']].head(20)

    ball  wides  noballs  legal_ball
0    0.1    0.0      0.0           1
1    0.2    0.0      0.0           1
2    0.3    0.0      0.0           1
3    0.4    0.0      0.0           1
4    0.5    0.0      0.0           1
5    0.6    0.0      0.0           1
6    1.1    0.0      0.0           1
7    1.2    0.0      0.0           1
8    1.3    0.0      0.0           1
9    1.4    0.0      0.0           1
10   1.5    0.0      0.0           1
11   1.6    0.0      0.0           1
12   2.1    0.0      0.0           1
13   2.2    0.0      0.0           1
14   2.3    0.0      0.0           1
15   2.4    0.0      0.0           1
16   2.5    0.0      0.0           1
17   2.6    0.0      0.0           1
18   3.1    0.0      0.0           1
19   3.2    0.0      0.0           1

In [57]:
second['balls_bowled'] = second.groupby('match_id')['legal_ball'].cumsum()

In [58]:
second[['ball','legal_ball','balls_bowled']].head(30)

    ball  legal_ball  balls_bowled
0    0.1           1             1
1    0.2           1             2
2    0.3           1             3
3    0.4           1             4
4    0.5           1             5
5    0.6           1             6
6    1.1           1             7
7    1.2           1             8
8    1.3           1             9
9    1.4           1            10
10   1.5           1            11
11   1.6           1            12
12   2.1           1            13
13   2.2           1            14
14   2.3           1            15
15   2.4           1            16
16   2.5           1            17
17   2.6           1            18
18   3.1           1            19
19   3.2           1            20
20   3.3           1            21
21   3.4           0            21
22   3.5           1            22
23   3.6           1            23
24   3.7           1            24
25   4.1           1            25
26   4.2           1            26
27   4.3           1            27
28   4.4           0            27
29   4.5           1            28

In [59]:
second['balls_bowled'].max()

120

In [60]:
second['balls_left'] = 120 - second['balls_bowled']

In [61]:
second[['ball','balls_bowled','balls_left']].head(10)

   ball  balls_bowled  balls_left
0   0.1             1         119
1   0.2             2         118
2   0.3             3         117
3   0.4             4         116
4   0.5             5         115
5   0.6             6         114
6   1.1             7         113
7   1.2             8         112
8   1.3             9         111
9   1.4            10         110

In [62]:
second['balls_left'].min()

0

In [63]:
second['crr'] = (second['current_score'] * 6) / second['balls_bowled']

In [64]:
second[['current_score','balls_bowled','crr']].head(20)

    current_score  balls_bowled        crr
0               1             1   6.000000
1               1             2   3.000000
2               1             3   2.000000
3               3             4   4.500000
4               7             5   8.400000
5              11             6  11.000000
6              11             7   9.428571
7              11             8   8.250000
8              12             9   8.000000
9              12            10   7.200000
10             12            11   6.545455
11             12            12   6.000000
12             12            13   5.538462
13             16            14   6.857143
14             17            15   6.800000
15             21            16   7.875000
16             22            17   7.764706
17             28            18   9.333333
18             29            19   9.157895
19             35            20  10.500000

In [65]:
second['rrr'] = (second['runs_left'] * 6) / second['balls_left']

In [66]:
second[['runs_left','balls_left','rrr']].tail(20)

        runs_left  balls_left        rrr
142283         38          19  12.000000
142284         37          18  12.333333
142285         37          17  13.058824
142286         36          16  13.500000
142287         35          15  14.000000
142288         35          14  15.000000
142289         34          13  15.692308
142290         30          12  15.000000
142291         29          11  15.818182
142292         27          10  16.200000
142293         27           9  18.000000
142294         26           8  19.500000
142295         24           7  20.571429
142296         18           6  18.000000
142297         17           5  20.400000
142298         15           4  22.500000
142299         15           3  30.000000
142300         14           2  42.000000
142301         13           1  78.000000
142302          9           0        inf

In [67]:
second['rrr'].max()

np.float64(inf)

In [68]:
second = second[second['balls_left'] != 0]

In [69]:
second['rrr'].max()

792.0

In [70]:
second.shape

(141840, 57)

In [71]:
second[second['rrr'] == second['rrr'].max()][
    ['match_id','runs_left','balls_left','rrr']
]

        match_id  runs_left  balls_left    rrr
116858    598027        132           1  792.0

In [72]:
second[['crr','rrr']].isnull().sum()

crr    0
rrr    0
dtype: int64

In [73]:
second[['crr','rrr']].describe()

                crr            rrr
count  1.418400e+05  141840.000000
mean            inf      10.856610
std             NaN      13.300473
min    0.000000e+00     -30.000000
25%    6.518519e+00       7.333333
50%    7.800000e+00       9.109091
75%    9.166667e+00      11.315789
max             inf     792.000000

In [74]:
final_df = second[['batting_team',
                   'bowling_team',
                   'city',
                   'runs_left',
                   'balls_left',
                   'wickets_left',
                   'target',
                   'crr',
                   'rrr',
                   'result']]

In [75]:
final_df.head(20)

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,target,crr,rrr,result
0,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,119,10,208,6.000000,10.436975,NaN
1,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,118,10,208,3.000000,10.525424,NaN
2,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,117,10,208,2.000000,10.615385,NaN
3,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,205,116,10,208,4.500000,10.603448,NaN
4,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,201,115,10,208,8.400000,10.486957,NaN
5,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,197,114,10,208,11.000000,10.368421,NaN
6,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,197,113,10,208,9.428571,10.460177,NaN
7,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,197,112,10,208,8.250000,10.553571,NaN
8,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,196,111,10,208,8.000000,10.594595,NaN
9,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,196,110,10,208,7.200000,10.690909,NaN
10,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,196,109,10,208,6.545455,10.788991,NaN
11,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,196,108,10,208,6.000000,10.888889,NaN
12,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,196,107,10,208,5.538462,10.990654,NaN
13,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,192,106,10,208,6.857143,10.867925,NaN
14,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,191,105,10,208,6.800000,10.914286,NaN
15,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,187,104,10,208,7.875000,10.788462,NaN
16,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,186,103,10,208,7.764706,10.834951,NaN
17,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,180,102,10,208,9.333333,10.588235,NaN
18,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,179,101,10,208,9.157895,10.633663,NaN
19,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,173,100,10,208,10.500000,10.380000,NaN

In [76]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 141840 entries, 0 to 142301
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   batting_team  141840 non-null  object
 1   bowling_team  141840 non-null  object
 2   city          135849 non-null  object
 3   runs_left     141840 non-null  int64
 4   balls_left    141840 non-null  int64
 5   wickets_left  141840 non-null  int64
 6   target        141840 non-null  int64
 7   crr           141840 non-null  float64
 8   rrr           141840 non-null  float64
 9   result        0 non-null       float64
dtypes: float64(3), int64(4), object(3)
memory usage: 11.9+ MB

In [77]:
final_df.isnull().sum()

batting_team         0
bowling_team         0
city              5991
runs_left            0
balls_left           0
wickets_left         0
target               0
crr                  0
rrr                  0
result          141840
dtype: int64

In [78]:
final_df.columns

Index(['batting_team', 'bowling_team', 'city', 'runs_left', 'balls_left',
       'wickets_left', 'target', 'crr', 'rrr', 'result'],
      dtype='object')

In [79]:
second['result'].value_counts(dropna=False)

result
NaN    141840
Name: count, dtype: int64

In [80]:
second[['batting_team','winner']].head()

                  batting_team               winner
0  Royal Challengers Bangalore  Sunrisers Hyderabad
1  Royal Challengers Bangalore  Sunrisers Hyderabad
2  Royal Challengers Bangalore  Sunrisers Hyderabad
3  Royal Challengers Bangalore  Sunrisers Hyderabad
4  Royal Challengers Bangalore  Sunrisers Hyderabad

In [81]:
import numpy as np

second['result'] = np.where(
    second['batting_team'] == second['winner'],
    1,
    0
)

/var/folders/l6/736l2wjj1cx0g8_mdb43qr8c0000gn/T/ipykernel_38047/4207221378.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second['result'] = np.where(

In [82]:
second['result'].value_counts()

result
1    73666
0    68174
Name: count, dtype: int64

In [83]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 141840 entries, 0 to 142301
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   batting_team  141840 non-null  object
 1   bowling_team  141840 non-null  object
 2   city          135849 non-null  object
 3   runs_left     141840 non-null  int64
 4   balls_left    141840 non-null  int64
 5   wickets_left  141840 non-null  int64
 6   target        141840 non-null  int64
 7   crr           141840 non-null  float64
 8   rrr           141840 non-null  float64
 9   result        0 non-null       float64
dtypes: float64(3), int64(4), object(3)
memory usage: 11.9+ MB

In [84]:
final_df['result'].value_counts()

Series([], Name: count, dtype: int64)

In [85]:
final_df = second[['batting_team',
                   'bowling_team',
                   'city',
                   'runs_left',
                   'balls_left',
                   'wickets_left',
                   'target',
                   'crr',
                   'rrr',
                   'result']]

In [86]:
final_df['result'].value_counts()

result
1    73666
0    68174
Name: count, dtype: int64

In [87]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 141840 entries, 0 to 142301
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   batting_team  141840 non-null  object
 1   bowling_team  141840 non-null  object
 2   city          135849 non-null  object
 3   runs_left     141840 non-null  int64
 4   balls_left    141840 non-null  int64
 5   wickets_left  141840 non-null  int64
 6   target        141840 non-null  int64
 7   crr           141840 non-null  float64
 8   rrr           141840 non-null  float64
 9   result        141840 non-null  int64
dtypes: float64(2), int64(5), object(3)
memory usage: 11.9+ MB

In [88]:
final_df = final_df.dropna()

In [89]:
final_df.shape

(135849, 10)

In [90]:
final_df

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,target,crr,rrr,result
0,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,119,10,208,6.000000,10.436975,0
1,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,118,10,208,3.000000,10.525424,0
2,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,117,10,208,2.000000,10.615385,0
3,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,205,116,10,208,4.500000,10.603448,0
4,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,201,115,10,208,8.400000,10.486957,0
...,...,...,...,...,...,...,...,...,...,...
142297,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,17,5,4,209,10.017391,20.400000,0
142298,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,15,4,4,209,10.034483,22.500000,0
142299,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,15,3,3,209,9.948718,30.000000,0
142300,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,14,2,3,209,9.915254,42.000000,0
142301,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,13,1,3,209,9.882353,78.000000,0

In [93]:
final_df.tail(20)

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,target,crr,rrr,result
142282,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,44,20,5,209,9.900000,13.200000,0
142283,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,38,19,5,209,10.158416,12.000000,0
142284,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,37,18,5,209,10.117647,12.333333,0
142285,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,37,17,5,209,10.019417,13.058824,0
142286,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,36,16,5,209,9.980769,13.500000,0
142287,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,35,15,5,209,9.942857,14.000000,0
142288,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,35,14,5,209,9.849057,15.000000,0
142289,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,34,13,5,209,9.813084,15.692308,0
142290,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,30,12,5,209,9.944444,15.000000,0
142291,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,29,11,4,209,9.908257,15.818182,0
142292,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,27,10,4,209,9.927273,16.200000,0
142293,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,27,9,4,209,9.837838,18.000000,0
142294,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,26,8,4,209,9.803571,19.500000,0
142295,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,24,7,4,209,9.823009,20.571429,0
142296,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,18,6,4,209,10.052632,18.000000,0
142297,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,17,5,4,209,10.017391,20.400000,0
142298,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,15,4,4,209,10.034483,22.500000,0
142299,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,15,3,3,209,9.948718,30.000000,0
142300,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,14,2,3,209,9.915254,42.000000,0
142301,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,13,1,3,209,9.882353,78.000000,0

In [94]:
final_df['batting_team'].nunique()

19

In [95]:
final_df['batting_team'].unique()

array(['Royal Challengers Bangalore', 'Rising Pune Supergiant',
       'Kolkata Knight Riders', 'Kings XI Punjab', 'Delhi Daredevils',
       'Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Chennai Super Kings', 'Rajasthan Royals', 'Delhi Capitals',
       'Punjab Kings', 'Gujarat Titans', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru', 'Deccan Chargers', 'Pune Warriors',
       'Kochi Tuskers Kerala', 'Rising Pune Supergiants'], dtype=object)

In [96]:
final_df['batting_team'] = final_df['batting_team'].replace({
    'Delhi Daredevils': 'Delhi Capitals'
})

final_df['bowling_team'] = final_df['bowling_team'].replace({
    'Delhi Daredevils': 'Delhi Capitals'
})

In [97]:
teams = [
    'Chennai Super Kings',
    'Delhi Capitals',
    'Kolkata Knight Riders',
    'Mumbai Indians',
    'Punjab Kings',
    'Rajasthan Royals',
    'Royal Challengers Bangalore',
    'Sunrisers Hyderabad',
    'Gujarat Titans',
    'Lucknow Super Giants'
]

In [98]:
final_df = final_df[
    final_df['batting_team'].isin(teams) &
    final_df['bowling_team'].isin(teams)
]

In [99]:
final_df.shape

(92269, 10)

In [100]:
sorted(final_df['batting_team'].unique())

['Chennai Super Kings',
 'Delhi Capitals',
 'Gujarat Titans',
 'Kolkata Knight Riders',
 'Lucknow Super Giants',
 'Mumbai Indians',
 'Punjab Kings',
 'Rajasthan Royals',
 'Royal Challengers Bangalore',
 'Sunrisers Hyderabad']

In [101]:
final_df['batting_team'] = final_df['batting_team'].replace({
    'Royal Challengers Bangalore':'Royal Challengers Bengaluru'
})

final_df['bowling_team'] = final_df['bowling_team'].replace({
    'Royal Challengers Bangalore':'Royal Challengers Bengaluru'
})

/var/folders/l6/736l2wjj1cx0g8_mdb43qr8c0000gn/T/ipykernel_38047/945847316.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['batting_team'] = final_df['batting_team'].replace({
/var/folders/l6/736l2wjj1cx0g8_mdb43qr8c0000gn/T/ipykernel_38047/945847316.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['bowling_team'] = final_df['bowling_team'].replace({

In [102]:
final_df

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,target,crr,rrr,result
0,Royal Challengers Bengaluru,Sunrisers Hyderabad,Hyderabad,207,119,10,208,6.000000,10.436975,0
1,Royal Challengers Bengaluru,Sunrisers Hyderabad,Hyderabad,207,118,10,208,3.000000,10.525424,0
2,Royal Challengers Bengaluru,Sunrisers Hyderabad,Hyderabad,207,117,10,208,2.000000,10.615385,0
3,Royal Challengers Bengaluru,Sunrisers Hyderabad,Hyderabad,205,116,10,208,4.500000,10.603448,0
4,Royal Challengers Bengaluru,Sunrisers Hyderabad,Hyderabad,201,115,10,208,8.400000,10.486957,0
...,...,...,...,...,...,...,...,...,...,...
142297,Royal Challengers Bengaluru,Sunrisers Hyderabad,Bangalore,17,5,4,209,10.017391,20.400000,0
142298,Royal Challengers Bengaluru,Sunrisers Hyderabad,Bangalore,15,4,4,209,10.034483,22.500000,0
142299,Royal Challengers Bengaluru,Sunrisers Hyderabad,Bangalore,15,3,3,209,9.948718,30.000000,0
142300,Royal Challengers Bengaluru,Sunrisers Hyderabad,Bangalore,14,2,3,209,9.915254,42.000000,0
142301,Royal Challengers Bengaluru,Sunrisers Hyderabad,Bangalore,13,1,3,209,9.882353,78.000000,0

In [103]:
final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [104]:
final_df[['batting_team','bowling_team']].head(20)

             batting_team                 bowling_team
0     Chennai Super Kings             Rajasthan Royals
1          Mumbai Indians                 Punjab Kings
2            Punjab Kings               Gujarat Titans
3   Kolkata Knight Riders          Sunrisers Hyderabad
4          Mumbai Indians        Kolkata Knight Riders
5     Sunrisers Hyderabad             Rajasthan Royals
6        Rajasthan Royals  Royal Challengers Bengaluru
7     Sunrisers Hyderabad               Mumbai Indians
8     Sunrisers Hyderabad                 Punjab Kings
9   Kolkata Knight Riders          Sunrisers Hyderabad
10  Kolkata Knight Riders          Chennai Super Kings
11  Kolkata Knight Riders               Mumbai Indians
12  Kolkata Knight Riders               Mumbai Indians
13       Rajasthan Royals          Chennai Super Kings
14         Mumbai Indians             Rajasthan Royals
15    Chennai Super Kings  Royal Challengers Bengaluru
16       Rajasthan Royals               Delhi Capitals
17         Mumbai Indians          Sunrisers Hyderabad
18    Chennai Super Kings               Gujarat Titans
19         Gujarat Titans         Lucknow Super Giants

In [105]:
final_df.sample()

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,target,crr,rrr,result
32457,Mumbai Indians,Sunrisers Hyderabad,Visakhapatnam,120,54,3,178,5.272727,13.333333,0

In [125]:
x_train[x_train['rrr'] == np.inf]

Empty DataFrame
Columns: [batting_team, bowling_team, city, runs_left, balls_left, wickets_left, target, crr, rrr]
Index: []

In [126]:
final_df[final_df['rrr'] == np.inf]

Empty DataFrame
Columns: [batting_team, bowling_team, city, runs_left, balls_left, wickets_left, target, crr, rrr, result]
Index: []

In [127]:
final_df.describe()

,runs_left,balls_left,wickets_left,target,crr,rrr,result
count,92269.000000,92269.000000,92269.000000,92269.000000,9.226900e+04,92269.000000,92269.000000
mean,96.876632,63.194442,7.521367,173.767712,inf,10.888367,0.525670
std,52.339295,33.216232,2.163744,32.930524,NaN,12.883463,0.499343
min,-15.000000,1.000000,0.000000,63.000000,0.000000e+00,-30.000000,0.000000
25%,56.000000,35.000000,6.000000,152.000000,6.600000e+00,7.406250,0.000000
50%,96.000000,64.000000,8.000000,172.000000,7.897959e+00,9.191489,1.000000
75%,135.000000,92.000000,9.000000,195.000000,9.259259e+00,11.415929,1.000000
max,287.000000,120.000000,10.000000,287.000000,inf,714.000000,1.000000

In [129]:
final_df = final_df[final_df['balls_left'] != 120]

In [130]:
final_df[final_df['crr'] == np.inf]

Empty DataFrame
Columns: [batting_team, bowling_team, city, runs_left, balls_left, wickets_left, target, crr, rrr, result]
Index: []

In [131]:
x = final_df.drop('result', axis=1)
y = final_df['result']

In [132]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [133]:
x_train.shape

(73772, 9)

In [134]:
trf.fit(x_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('trf', OneHotEncoder(handle_unknown='ignore'),
                                 ['batting_team', 'bowling_team', 'city'])])

In [135]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

pipe = Pipeline([
    ('step1', trf),
    ('step2', LogisticRegression())
])

In [136]:
pipe.fit(x_train,y_train)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression())])

In [137]:
y_pred = pipe.predict(x_test)

In [138]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.8055736282801995

In [139]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[6783, 1917],
       [1669, 8075]])

In [140]:
pipe.predict_proba(x_test)

array([[0.90546676, 0.09453324],
       [0.45345856, 0.54654144],
       [0.11161918, 0.88838082],
       ...,
       [0.46322181, 0.53677819],
       [0.28717511, 0.71282489],
       [0.15228869, 0.84771131]], shape=(18444, 2))

In [141]:
import pickle

pickle.dump(pipe,open('pipe.pkl','wb'))

In [142]:
import os

os.listdir()

['D.csv',
 'S.csv',
 'Untitled.ipynb',
 'ss.csv',
 '.ipynb_checkpoints',
 'pipe.pkl']

In [143]:
import pickle

pickle.dump(final_df, open('df.pkl','wb'))

In [144]:
import os
os.listdir()

['D.csv',
 'S.csv',
 'Untitled.ipynb',
 'ss.csv',
 'df.pkl',
 '.ipynb_checkpoints',
 'pipe.pkl']

In [146]:
import os
os.getcwd()

'/Users/ankitasharma/IPL PROJECT'

In [147]:
import os
os.listdir()

['D.csv',
 'S.csv',
 'ipl.ipynb',
 'ss.csv',
 'df.pkl',
 '.ipynb_checkpoints',
 'pipe.pkl']